#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

# Instalation of the nginx server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/index.html
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html

sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html/;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart