#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

# Instalation of the nginx server
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
