#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

# Instalation of the nginx server
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=DHITmcKUGik;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
    }
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
