#!/usr/bin/env bash
# Installs HAProxy load balancer with the following configurations:

sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*

sudo printf %s "listen http-in
        bind *:80
        mode http
        balance roundrobin
        server  1164-web-01 54.158.45.251:80 check
        server 1164-web-02 100.24.7.183:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
