#!/usr/bin/env bash
# Installs HAProxy load balancer with the following configurations:

sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*

sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1164-web-01 54.158.45.251:80 check\n\tserver 1164-web-02  100.24.7.183:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
