#!/usr/bin/env bash
# Configure nginx sever to listen in port 80

sudo rm /etc/nginx/sites-enabled/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
