#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/holbertonscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#  receiving a SIGQUIT or SIGTERM.

echo $$ > '/var/run/holbertonscript.pid'

while true
do
    trap 'echo "I hate the kill command" &&
        rm "/var/run/holbertonscript.pid" && exit' SIGTERM
    trap 'rm "/var/run/holbertonscript.pid"&& exit' SIGQUIT
    trap 'echo "Y U no love me?!"' SIGINT
    echo 'To infinity and beyond'
    sleep 2
done