#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read -r user pass id group info home command 
do
    echo "The user $user is part of the $group gang,"\
    "lives in $home and rides $command."\
    "$id's place is protected by the passcode $pass,"\
    "more info about the user here: $info"
done < "/etc/passwd"