#!/usr/bin/env bash
# Configures a ufw firewall

apt-get install ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw reload
